server:
  port: 8085
  http2:
    enabled: true
spring:
  boot:
    admin:
      client:
        username: admin
        password: admin-password
        url: http://localhost:8084


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/diplomaproject?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=GMT
    username: root
    password: root
  flyway:
    enabled: false
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
doc:
  report:
    pathToReportTemplate: src\\main\\resources\\static\\docx_templates\\template_report.docx
    placeholderRegexp: \{\{([a-zA-z0-9]+)}}
    placeholderColor: 7030A0

  scoreList:
    pathToScoreListTemplate: src\\main\\resources\\static\\docx_templates\\template_score_list.docx
    placeholderRegexp: \{\{(.+?)}}

  func:
    argsSeparator: \,
    tableFiledSeparator: \.
    sum:
      validateRegexp: sum\([A-Za-z0-9,.]+\)
      prefix: sum
    isSmth:
      validateRegexp: issmth\([A-Za-z0-9,.]+\)
      prefix: issmth

